apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone
        role: blue
    spec:
      containers:
      - name: capstone-container
        image: arobsco/capstone:v1
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80