apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
        role: green
    spec:
      containers:
      - name: app
        image: arobsco/capstone:v2
        ports:
        - containerPort: 80