kind: Service
apiVersion: v1
metadata:
  name: capstone
  labels:
    app: capstone
    role: green
spec:
  type: LoadBalancer
  selector:
    app: capstone
    role: green
  ports:
    - port: 80
      targetPort: 80